name: Evo Monitor
on:
  schedule:
    - cron: '30 3 * * *'   # JST 12:30
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install --no-cache-dir requests beautifulsoup4 aiohttp python-dotenv

      - id: digest
        run: python evo_monitor.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      # ----- ここから追記 -----
      - name: Save digest markdown
        if: steps.digest.outputs.summary != ''
        run: |
          FILE=daily/EVO_DIGEST_$(date +'%F').md
          mkdir -p daily
          echo "${{ steps.digest.outputs.summary }}" > "$FILE"

      - name: Commit & push digest
        if: steps.digest.outputs.summary != ''
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add daily digest $(date +'%F')"
          file_pattern: daily/*.md
      # ----- 追記ここまで -----
