name: Evo Monitor
on:
  schedule:
    # JST 08:00-08:45 → 前日の 23:00-23:45 UTC
    - cron: '*/15 23 * * *'
    # JST 09:00-16:45 → 当日 00:00-07:45 UTC
    - cron: '*/15 0-7 * * *'
    # JST 17:00 ぴったり → 当日 08:00 UTC
    - cron: '0 8 * * *'
  workflow_dispatch:   # 手動トリガーはそのまま残す

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install --no-cache-dir requests beautifulsoup4 aiohttp python-dotenv
      - run: python evo_monitor.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
